In [1]:
import numpy as np

In [3]:
array = np.arange(10, dtype='int32')

In [5]:
array += 1

In [7]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [9]:
import numpy as np

In [11]:
n1 = np.array([1], dtype='uint8')

In [13]:
n255 = np.array([255],dtype='uint8')

In [15]:
n1+n255

array([0], dtype=uint8)

In [17]:
import numpy as np

In [30]:
demo = np.array([1,2,3, np.nan])

In [32]:
demo

array([ 1.,  2.,  3., nan])

In [34]:
demo.dtype

dtype('float64')

In [60]:
small_values = [1,00,127]
large_values = [2**31,2**63,2**100]
missing_values = [None,1,-45]

In [40]:
import pandas as pd

In [42]:
small_ser = pd.Series(small_values)

In [44]:
small_ser

0      1
1      0
2    127
dtype: int64

In [46]:
small_ser.astype('int8')

0      1
1      0
2    127
dtype: int8

In [48]:
small_ser = pd.Series(small_values,dtype='int8')

In [50]:
small_ser

0      1
1      0
2    127
dtype: int8

In [52]:
small_ser_pa = pd.Series(small_values, dtype='int8[pyarrow]')

In [54]:
small_ser_pa

0      1
1      0
2    127
dtype: int8[pyarrow]

In [64]:
large_ser = pd.Series(large_values)

In [66]:
large_ser

0                         2147483648
1                9223372036854775808
2    1267650600228229401496703205376
dtype: object

In [68]:
large_ser = pd.Series(large_values, dtype='int64[pyarrow]')

OverflowError: Python int too large to convert to C long

In [70]:
missing_ser = pd.Series(missing_values)

In [72]:
missing_ser

0     NaN
1     1.0
2   -45.0
dtype: float64

In [74]:
missing_ser_pa = pd.Series(missing_values, dtype='int8[pyarrow]')

In [76]:
missing_ser_pa

0    <NA>
1       1
2     -45
dtype: int8[pyarrow]

In [82]:
medium_values = [2**15+5, 2**31-8, 2**63]
medium_ser = pd.Series(medium_values)
medium_ser

0                  32773
1             2147483640
2    9223372036854775808
dtype: uint64

In [84]:
medium_ser.astype('int8')

0    5
1   -8
2    0
dtype: int8

In [86]:
medium_ser.astype('int8[pyarrow]')

ArrowInvalid: Integer value 32773 not in range: 0 to 127

In [92]:
float_vals = [1.5,2.7,127.0]
float_missing = [None, 1.5, -45.0]
float_rain = [1.5, 2.7, 0.0, 'T', 1.5, 0]

In [96]:
pd.Series(float_vals)

0      1.5
1      2.7
2    127.0
dtype: float64

In [98]:
pd.Series(float_missing)

0     NaN
1     1.5
2   -45.0
dtype: float64

In [100]:
pd.Series(float_rain)

0    1.5
1    2.7
2    0.0
3      T
4    1.5
5      0
dtype: object

In [102]:
pd.Series(float_vals, dtype='float64[pyarrow]')

0      1.5
1      2.7
2    127.0
dtype: double[pyarrow]

In [104]:
pd.Series(float_missing, dtype='float64[pyarrow]')

0    <NA>
1     1.5
2   -45.0
dtype: double[pyarrow]

In [106]:
pd.Series(float_rain)

0    1.5
1    2.7
2    0.0
3      T
4    1.5
5      0
dtype: object

In [108]:
pd.Series(float_rain).replace('T', '0.0').astype('float64')

0    1.5
1    2.7
2    0.0
3    0.0
4    1.5
5    0.0
dtype: float64

In [114]:
pd.Series(float_rain).replace('T','0.0').astype('float64[pyarrow]')

ArrowInvalid: Could not convert '0.0' with type str: tried to convert to double

In [116]:
pd.Series(float_rain).replace('T', 0).astype('float64[pyarrow]')

/var/folders/j1/_rvyqj0d1tbbbrpqmjwvjfz80000gn/T/ipykernel_37535/2912682391.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pd.Series(float_rain).replace('T', 0).astype('float64[pyarrow]')


0    1.5
1    2.7
2    0.0
3    0.0
4    1.5
5    0.0
dtype: double[pyarrow]

In [124]:
pd.Series(float_rain).replace('T', '0.0').astype('float').astype('float64[pyarrow]')

0    1.5
1    2.7
2    0.0
3    0.0
4    1.5
5    0.0
dtype: double[pyarrow]

In [126]:
import pyarrow as pa
import pandas as pd

In [130]:
string_pa = pd.ArrowDtype(pa.string())

In [132]:
text_freeform = ['My name is Jeff', 'I like pandas', 'I like programming']
text_with_missing = ['My name is Jeff', None, 'I like programming']

In [134]:
pd.Series(text_freeform)

0       My name is Jeff
1         I like pandas
2    I like programming
dtype: object

In [136]:
pd.Series(text_with_missing)

0       My name is Jeff
1                  None
2    I like programming
dtype: object

In [144]:
string_pa = pd.ArrowDtype(pa.string())
tf1 = pd.Series(text_freeform, dtype=string_pa)
tf1

0       My name is Jeff
1         I like pandas
2    I like programming
dtype: string[pyarrow]

In [150]:
tf2 = pd.Series(text_freeform, dtype='string[pyarrow]')
tf2

0       My name is Jeff
1         I like pandas
2    I like programming
dtype: string

In [152]:
tf1.dtype == tf2.dtype

False

In [162]:
string_pa = pd.ArrowDtype(pa.string())
pd.Series(text_with_missing, dtype=string_pa)

0       My name is Jeff
1                  <NA>
2    I like programming
dtype: string[pyarrow]

In [164]:
states = ['CA', 'NY', 'TX']
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [166]:
pd.Series(states, dtype='category')

0    CA
1    NY
2    TX
dtype: category
Categories (3, object): ['CA', 'NY', 'TX']

In [176]:
pd.Series(months, dtype='category')

0     Jan
1     Feb
2     Mar
3     Apr
4     May
5     Jun
6     Jul
7     Aug
8     Sep
9     Oct
10    Nov
11    Dec
dtype: category
Categories (12, object): ['Apr', 'Aug', 'Dec', 'Feb', ..., 'May', 'Nov', 'Oct', 'Sep']

pd.Series(months, dtype='category').sort_values()

In [182]:
month_cat = pd.CategoricalDtype(categories=months,ordered=True)

In [184]:
pd.Series(months, dtype=month_cat).sort_values()

0     Jan
1     Feb
2     Mar
3     Apr
4     May
5     Jun
6     Jul
7     Aug
8     Sep
9     Oct
10    Nov
11    Dec
dtype: category
Categories (12, object): ['Jan' < 'Feb' < 'Mar' < 'Apr' ... 'Sep' < 'Oct' < 'Nov' < 'Dec']

In [188]:
month_cat = pd.CategoricalDtype(categories = months, ordered=True)
pd.Series(months, dtype=month_cat).sort_values()

0     Jan
1     Feb
2     Mar
3     Apr
4     May
5     Jun
6     Jul
7     Aug
8     Sep
9     Oct
10    Nov
11    Dec
dtype: category
Categories (12, object): ['Jan' < 'Feb' < 'Mar' < 'Apr' ... 'Sep' < 'Oct' < 'Nov' < 'Dec']

In [190]:
pd.Series(months, dtype=string_pa).astype(month_cat)

0     Jan
1     Feb
2     Mar
3     Apr
4     May
5     Jun
6     Jul
7     Aug
8     Sep
9     Oct
10    Nov
11    Dec
dtype: category
Categories (12, object): ['Jan' < 'Feb' < 'Mar' < 'Apr' ... 'Sep' < 'Oct' < 'Nov' < 'Dec']

In [192]:
import datetime as dt
dt_list = [dt.datetime(2020, 1,1, 4, 30), dt.datetime(2020,1,2),dt.datetime(2020,1,3,)]

In [194]:
string_dates = ['2020-01-01 04:30:00','2020-01-02 00:00:00', '2020-01-03 00:00:00']

In [196]:
string_dates_missing = ['2020-01-01 4:30', None, '2020-01-03']
epoch_dates = [1577836800,1577923200,1578009600]

In [198]:
pd.Series(dt_list)

0   2020-01-01 04:30:00
1   2020-01-02 00:00:00
2   2020-01-03 00:00:00
dtype: datetime64[ns]

In [200]:
pd.Series(string_dates,dtype='datetime64[ns]')

0   2020-01-01 04:30:00
1   2020-01-02 00:00:00
2   2020-01-03 00:00:00
dtype: datetime64[ns]

In [202]:
pd.Series(string_dates_missing, dtype='datetime64[ns]')

0   2020-01-01 04:30:00
1                   NaT
2   2020-01-03 00:00:00
dtype: datetime64[ns]

In [206]:
pd.Series(epoch_dates, dtype='datetime64[ns]')

0   1970-01-01 00:00:01.577836800
1   1970-01-01 00:00:01.577923200
2   1970-01-01 00:00:01.578009600
dtype: datetime64[ns]

In [208]:
pd.Series(epoch_dates, dtype='datetime64[s]')

0   2020-01-01
1   2020-01-02
2   2020-01-03
dtype: datetime64[s]

In [210]:
pd.Series(dt_list, dtype='timestamp[ns][pyarrow]')

0    2020-01-01 04:30:00
1    2020-01-02 00:00:00
2    2020-01-03 00:00:00
dtype: timestamp[ns][pyarrow]

In [212]:
pd.Series(string_dates, dtype='timestamp[ns][pyarrow]')

0    2020-01-01 04:30:00
1    2020-01-02 00:00:00
2    2020-01-03 00:00:00
dtype: timestamp[ns][pyarrow]

In [214]:
pd.Series(epoch_dates).astype('timestamp[s][pyarrow]')

0    2020-01-01 00:00:00
1    2020-01-02 00:00:00
2    2020-01-03 00:00:00
dtype: timestamp[s][pyarrow]